config/routes.rb
Rails.application.routes.draw do
    
    
  get 'follows/create'
  get 'follows/destroy'
    root to: "application#homepage"
    
    get 'login', to: 'sessions#show_login_form'
    post 'login', to: 'sessions#login_user'
    delete 'logout', to: 'sessions#logout_user'
    get 'profile', to: 'posts#index'

    get 'feed', to: 'users#feed'


    # post 'posts/:id', to: 'posts#create_comment'
    
    resources :users do 
      resources :follows
    end
      
    resources :posts do 
        resources :zens
        resources :comments
      end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    
    has_many :posts
    has_many :comments, through: :posts
    has_many :zens, through: :posts

    has_many :followed_users, foreign_key: :follower_id, class_name: 'Follow', dependent: :destroy
    has_many :following_users, foreign_key: :followee_id, class_name: 'Follow', dependent: :destroy
    
    has_many :followees, through: :followed_users
    has_many :followers, through: :following_users

    def follow(user)
        followed_users.create(followee_id: user.id)
    end

    def unfollow(user)
        # byebug
        self.followees.delete(user)
    end

    def following?(user)
        followees.include?(user)
    end
    
    def guru_status
        if self.zens.count < 5
            return "Baby Guru"
        else
            return "Master Guru"
        end
    end

     
    def feed
        posts = self.followees.map do |followee| 
            followee.posts
        end.flatten 
    end

    def already_zen?(post)
        Zen.where(user_id: self.id, post_id: post.id).exists?
    end

end

app/controllers/guru/users_controller.rb
class Guru::UsersController < ApplicationController
   
    before_action :find_user, only: [:show, :edit, :update, :destroy]

    def index
        @users = User.all
    end

    def show
    end

    def new
        @user = User.new
    end

    def create
        @user = User.create(user_params)
        redirect_to guru_user_path(@user)
    end

    def edit
    end

    def update
        @user.update(user_params)
        redirect_to guru_user_path(@user)
    end

    def destroy
        @user.destroy
        redirect_to guru_users_path
    end

    private

    def find_user
        @user = User.find(params[:id])
    end

    def user_params
        params.require(:user).permit(:first_name, :last_name, :about, :interests)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   
    before_action :find_user, only: [:show, :edit, :update, :destroy]
    # before_action :authorized, except: :homepage
    def index
        @users = User.all
    end

    def show
    end

    def new
        @user = User.new
    end

    def create
        @user = User.create(user_params)
        redirect_to user_path(@user)
    end

    def edit
    end

    def update
        @user.update(user_params)
        redirect_to users_path(@user)
    end

    def destroy
        @user.destroy
        redirect_to users_path
    end

    private

    def find_user
        @user = User.find(params[:id])
    end

    def user_params
        params.require(:user).permit(:name, :username, :occupation, :quote, :photo_url, :password)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_form.html.erb
<%=form_for @user do |f|%>
<<<<<<< HEAD
<%=f.label :name%>
<%=f.text_field :name%>
<%=f.label :occupation%>
<%=f.text_field :occupation%>
<%=f.label :quote%>
<%=f.text_field :quote%>
<%=f.label :password%>
<%=f.password_field :password%>
<%=f.label :password_confirmation%>
<%=f.password_field :password_confirmation%>
=======
<div><%=f.label :name%>
<%=f.text_field :name%></div>
<div><%=f.label :occupation%>
<%=f.text_field :occupation%></div>
<div><%=f.label :quote%>
<%=f.text_area :quote%></div>
>>>>>>> ee3eb6f363c2d37ca1650d62aca83491f6544260
<div>
<%=f.submit%>
<%end%>
</div>
<br>
<%=button_to "Return to List of Users", users_path, method: "get"%>

app/views/users/edit.html.erb
<h1>Edit User</h1>


<%= render partial: "user_form"%>

app/views/users/feed.html.erb
<div class = 'center'><img src= "<%= current_user.photo_url %>" alt= "profile image" height="100" width="100"></div>
<h1 class = 'center'>Your Feed</h1>

<div class = 'center'>Followers: <%=current_user.followers.count%> | Following: <%=current_user.followees.count%></div>
<br>
<ul>
<%current_user.feed.each do |post|%>
<li><%=link_to post.title, post_path(post)%> | by <%=link_to post.user.name, user_path(post.user)%> </li>
<div> Zens: <%=post.zens.count%> | Comments: <%=post.comments.count%></div>
<%end%>
</ul>

<%=button_to "Create a Post", new_post_path, method: 'get'%> 

app/views/users/index.html.erb
<h1 class = 'center'>List of Users</h1>

<ul>
<%@users.each do |user|%>
<li><%=link_to user.name, user_path(user)%></li>
<%end%>
</ul>


<%=link_to "Create a New User", new_user_path%>
<br><br>
<%=button_to "Explore", posts_path, method: "get"%>

app/views/users/new.html.erb
<h1>Create User</h1>


<%= render partial: "user_form"%>

app/views/users/show.html.erb
<br>
<div class = 'center'><img src= "<%= @user.photo_url %>" alt= "profile image" height="100" width="100"></div>
<div class = 'center'><h3><%=@user.name%></h3></div>
<div class = 'center'>Guru Status: <%=@user.guru_status%></div> 
<br>
<% if !current_user.following?(@user)%>
     <div class = 'center'>   <%=button_to "Follow", user_follows_path(@user), method: "post"%></div>
    <% else %>
       <div class = 'center'> <%=button_to "Unfollow", user_follow_path(@user), method: "delete"%></div>
    <%end%>


  
<div class = 'center'>Followers | <%=@user.followers.count%></div>
<div class = 'center'>Following | <%=@user.followees.count%></div>
<br>
<div><h3>Occupation:</h3> <%=@user.occupation%></div>
<br>
<div><h3>Favorite Quote:</h3> <%=@user.quote%> </div>
<br>
<h3>Posts:</h3>
<ul>
    <%@user.posts.each do |post|%>
    <li><%=link_to post.title, post_path(post.id)%> | Zens: <%=post.zens.count%></li>
    <%end%>
</ul>


<% if current_user.id == @user.id %>
    <%=button_to "Edit Your Profile", edit_user_path(@user), method: 'get'%>
    <%=button_to "Delete Profile", user_path(@user), method: "delete"%>
<% else %>
    <%=button_to "Back to Explore", posts_path, method: "get"%> 
<%end%>