config/routes.rb
Rails.application.routes.draw do
    
    
  get 'follows/create'
  get 'follows/destroy'
    root to: "application#homepage"
    
    get 'login', to: 'sessions#show_login_form'
    post 'login', to: 'sessions#login_user'
    delete 'logout', to: 'sessions#logout_user'
    get 'profile', to: 'posts#index'

    get 'feed', to: 'users#feed'


    # post 'posts/:id', to: 'posts#create_comment'
    
    resources :users do 
      resources :follows
    end
      
    resources :posts do 
        resources :zens
        resources :comments
      end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :destroy
    has_many :zens, dependent: :destroy

end

app/controllers/guru/posts_controller.rb
class Guru::PostsController < ApplicationController

    before_action :find_post, only: [:show, :edit, :update, :destroy]

    def index
        @posts = Post.all
    end

    def show
        @new_comment = Comment.new
    end

    def new
        @post = Post.new
    end

    def create
        @post = Post.create(post_params)
        redirect_to guru_post_path(@post)
    end

    def edit
    end

    def update
        @post.update(post_params)
        redirect_to guru_post_path(@post)
    end

    def destroy
        @post.destroy
        redirect_to guru_posts_path
    end

    private

    def find_post
        @post = Post.find(params[:id])
    end

    def post_params
        params.require(:post).permit(:description, :url, :media_type, :user_id)
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    before_action :find_post, only: [:show, :edit, :update, :destroy]
    
    def index
        # @posts = Post.left_joins(:zens).group(:post_id).order('COUNT(post_id) DESC')
        @posts = Post.all.includes(:zens, :comments, :user)
        @posts = @posts.sort {|a, b| b.zens.size <=> a.zens.size }
    end

    def show
        @new_comment = Comment.new
    end

    # def create_comment
    #     @post = Post.find(params[:id])
    #     Comment.create(text: params[:comment][:text], user_id: current_user.id, post_id: params[:id])
    #     redirect_to post_path(@post)
    # end

    def new
        @post = Post.new
    end

    def create
        @post = Post.create(post_params)
        redirect_to post_path(@post)
    end

    def edit
    end

    def update
        @post.update(post_params)
        redirect_to post_path(@post)
    end

    def destroy
        @post.destroy
        redirect_to posts_path
    end

    private

    def find_post
        @post = Post.find(params[:id])
    end

    def post_params
        params.require(:post).permit(:title, :description, :media_type, :user_id, :media_link)
    end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post_form.html.erb
<%=form_for @post do |f|%>
<%=f.label :title %>
<%=f.text_field :title %>
<div>
<%=f.label :media_link, "Link"%>
<%=f.text_field :media_link %>
</div>
<div>
<%=f.label :description %>
<%=f.text_area :description %>
</div>
<%=f.label :media_type, "Type of Content"%>
<%=f.select :media_type, ['Article', 'Podcast', 'Video', 'Book']%>
<div>
<%=f.submit%>
<%end%>
</div>
<br>
<%=button_to "Return Home", feed_path, method: "get"%>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>


<%= render partial: "post_form"%>

app/views/posts/index.html.erb
<h1 class = 'center'>Calm Down</h1>
<br>
<ul>
<%@posts.each do |post|%>
<li><%=link_to post.title, post_path(post.id)%> | by <%=link_to post.user.name, user_path(post.user)%> </li>
<div> Zens: <%=post.zens.length%> | Comments: <%=post.comments.length%></div>
<%end%>
</ul>


<%=button_to "Create a Post", new_post_path, method: 'get'%>

app/views/posts/new.html.erb
<h1 class = 'center'>What Calms You?</h1>


<%= render partial: "post_form"%>

app/views/posts/show.html.erb
<br><br>
<div class = 'center'><img src= "<%= @post.user.photo_url %>" alt= "user image" height="100" width="100"></div>
<div class = 'center'><h3><%=link_to @post.user.name, user_path(@post.user.id)%>, <%=@post.user.guru_status%></h3></div>

<% if !current_user.following?(@post.user)%>
       <div class = 'center'> <%=button_to "Follow", user_follows_path(@post.user), method: "post"%></div>
    <% else %>
      <div class = 'center'>  <%=button_to "Unfollow", user_follow_path(@post.user), method: "delete"%></div>
    <%end%>

 
<br>
<div><%=link_to @post.title, @post.media_link, target: :_blank%> <h6>Posted on <%=@post.created_at.strftime("%A, %B %-d, %Y")%></h6></div>
<div><%=@post.description%></div>

<div><%=@post.media_type%> | <%=@post.zens.size%> <%= (@post.zens.size) == 1 ? 'Zen' : 'Zens'%><%=button_to "Zen", post_zens_path(@post), method: "post"%></div>

<div class = 'error_text'> 
<%if flash[:notice]%>
   <div class = 'error'><%= flash[:notice] %></div>
<%end%>
</div>

<br>

<h4>Comments:</h4>
<ul>
<%@post.comments.each do |comment|%>
<li><%=comment.text%><br><%=link_to comment.user.name, user_path(comment.user)%> on <%=comment.created_at.strftime("%A, %B %-d, %Y")%> 
    <%if current_user.id == comment.user.id%>
        <%=button_to "Delete this Comment", post_comment_path(post_id: @post.id, id: comment.id), method: "delete"%></li>
    <%else%>
    <%end%>
<%end%>
</ul>


<div>
<h4>Add Comment:</h4>
<%=form_for @new_comment, url: post_comments_path(@post.id) do |f|%>
<%=f.text_area :text, maxlength: 200%>
<%=f.submit "Create Comment"%>
<%end%>
</div>

<div>
<% if current_user.id == @post.user.id%>
    <%=button_to "Delete Post", post_path(@post), method: "delete"%>
<% else %>
    <%=button_to "Back to Explore", posts_path, method: "get"%> 
<%end%>
</div>